# Generated by Django 4.2 on 2023-04-26 01:30

import animais.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.global_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abrigos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, validators=[tools.global_validator.GlobalValidator.validar_nome])),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, validators=[tools.global_validator.GlobalValidator.validar_nome])),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='P', max_length=1, validators=[animais.validators.RacaValidator.validar_porte])),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animais.especie')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'Disponível para adoção'), ('A', 'Adotado'), ('E', 'Em processo de adoção')], default='D', max_length=20)),
                ('foto', models.ImageField(upload_to='animais_images/%d-%b')),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('entrada_abrigo', models.DateField(auto_now_add=True)),
                ('abrigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abrigos.abrigo')),
                ('adotado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animais.raca')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
