# Generated by Django 4.2 on 2023-05-01 18:47

import animais.validators_dir.animal
import animais.validators_dir.especie
import animais.validators_dir.raca
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='entrada_abrigo',
            field=models.DateField(auto_now_add=True, validators=[animais.validators_dir.animal.AnimalValidator.validar_entrada_abrigo]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nascimento',
            field=models.DateField(blank=True, null=True, validators=[animais.validators_dir.animal.AnimalValidator.validar_nascimento]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=50, validators=[animais.validators_dir.animal.AnimalValidator.validar_nome]),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(max_length=30, unique=True, validators=[animais.validators_dir.especie.EspecieValidator.validar_nome]),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nome',
            field=models.CharField(max_length=30, unique=True, validators=[animais.validators_dir.raca.RacaValidator.validar_nome]),
        ),
    ]
