# Generated by Django 4.2 on 2023-05-01 18:47

from django.db import migrations, models
import usuarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[usuarios.validators.UsuarioValidator.validar_email]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(validators=[usuarios.validators.UsuarioValidator.validar_nascimento, usuarios.validators.UsuarioValidator.validar_usuario_eh_de_maior]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=30, validators=[usuarios.validators.UsuarioValidator.validar_nome]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(max_length=30, validators=[usuarios.validators.UsuarioValidator.validar_nome]),
        ),
    ]
