# Generated by Django 4.2 on 2023-04-26 01:30

import abrigos.validators
from django.db import migrations, models
import tools.global_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, default='', upload_to='abrigos_images/%d-%b')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[tools.global_validator.GlobalValidator.validar_email], verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=11, unique=True, validators=[abrigos.validators.AbrigoValidator.validar_numero_de_celular])),
                ('cep', models.CharField(max_length=8, validators=[abrigos.validators.AbrigoValidator.validar_cep])),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Abrigo',
                'verbose_name_plural': 'Abrigos',
            },
        ),
    ]
