# Generated by Django 4.2 on 2023-05-01 18:47

import abrigos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrigo',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[abrigos.validators.AbrigoValidator.validar_email], verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='abrigo',
            name='nome',
            field=models.CharField(max_length=30, validators=[abrigos.validators.AbrigoValidator.validar_nome]),
        ),
    ]
